In [2]:
# 패키지 업로드
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
files.upload()

Saving finedust.csv to finedust.csv


{'finedust.csv': b'\xc3\xf8\xc1\xa4\xc0\xcf\xc0\xda,\xc3\xf8\xc1\xa4\xbd\xc3\xb0\xa3,\xc1\xf6\xbf\xaa,\xc1\xf6\xbf\xaa\xb8\xed,\xb5\xb5\xb7\xce\xb8\xed,\xbd\xc3\xc0\xdb\xc1\xa1,\xc1\xbe\xc1\xa1,\xb1\xe2\xbf\xc2,\xbd\xc0\xb5\xb5,\xc0\xe7\xba\xf1\xbb\xea\xb8\xd5\xc1\xf6 \xc6\xf2\xb1\xd5\xb3\xf3\xb5\xb5,\xbf\xc0\xbf\xb0\xb9\xfc\xb7\xca\r\n2021-07-01,9:44,\xbc\xad\xbf\xef,\xb1\xb8\xb7\xce\xb1\xb8,\xba\xce\xc0\xcf\xb7\xce,\xbc\xad\xbf\xef\xc6\xaf\xba\xb0\xbd\xc3 \xb1\xb8\xb7\xce\xb1\xb8 \xb1\xc3\xb5\xbf 197-10,\xbc\xad\xbf\xef\xc6\xaf\xba\xb0\xbd\xc3 \xb1\xb8\xb7\xce\xb1\xb8 \xbf\xc2\xbc\xf6\xb5\xbf 56,28,57,27,\xb8\xc5\xbf\xec\xc1\xc1\xc0\xbd\r\n2021-07-01,10:04,\xbc\xad\xbf\xef,\xb1\xb8\xb7\xce\xb1\xb8,\xbc\xad\xc7\xd8\xbe\xc8\xb7\xce,\xbc\xad\xbf\xef\xc6\xaf\xba\xb0\xbd\xc3 \xb1\xb8\xb7\xce\xb1\xb8 \xc7\xd7\xb5\xbf 211-22,\xbc\xad\xbf\xef\xc6\xaf\xba\xb0\xbd\xc3 \xb1\xb8\xb7\xce\xb1\xb8 \xb0\xb3\xba\xc0\xb5\xbf 243-2,28,58,18,\xb8\xc5\xbf\xec\xc1\xc1\xc0\xbd\r\n2021-07-01,10:28,\xbc\xad\

### 1. 결측값/중복값 처리 
한국환경공단에서 발표한 미세먼지 관련 자료를 분석해보겠습니다. <p>
<p>finedust.csv 파일을 사용 <p>
(이 파일은 공공기관 파일로, 인코딩이 utf-8이 아닌 cp949로 되어 있습니다)

In [ ]:
df = pd.read_csv('finedust.csv', encoding= 'cp949')

1-1) finedust.csv를 위에서부터 10행 출력해주세요.

In [5]:
df.head(10)

측정일자   측정시간  지역  지역명   도로명                    시작점  \
0  2021-07-01   9:44  서울  구로구   부일로    서울특별시 구로구 궁동 197-10   
1  2021-07-01  10:04  서울  구로구  서해안로    서울특별시 구로구 항동 211-22   
2  2021-07-01  10:28  서울  구로구   중앙로     서울특별시 구로구 고척동 63-5   
3  2021-07-01  10:35  서울  구로구   고척로    서울특별시 구로구 고척동 186-4   
4  2021-07-01  11:04  서울  구로구   오리로         서울특별시 구로구 궁동 5   
5  2021-07-01  11:49  서울  구로구   금오로     경기도 광명시 옥길동 667-21   
6  2021-07-01  11:57  서울  구로구   천왕로    서울특별시 구로구 천왕동 14-44   
7  2021-07-01  12:09  서울  구로구   개봉로    서울특별시 구로구 개봉동 372-1   
8  2021-07-01  12:23  서울  구로구   공원로  서울특별시 구로구 신도림동 422-10   
9  2021-07-01  12:30  서울  NaN   NaN   서울특별시 구로구 구로동 136-14   

                    종점    기온    습도  재비산먼지 평균농도  오염범례  
0     서울특별시 구로구 온수동 56  28.0  57.0        27.0  매우좋음  
1  서울특별시 구로구 개봉동 243-2  28.0  58.0        18.0  매우좋음  
2   서울특별시 구로구 고척동 1-15  29.0  54.0        33.0  매우좋음  
3   서울특별시 구로구 오류동 6-41  29.0  54.0        19.0  매우좋음  
4                  NaN  29.0  56.0        23.0  매우좋음  
5                  NaN  31.0   NaN        49.0  매우좋음  
6                  NaN  31.0  50.0        22.0  매우좋음  
7                  NaN  31.0  49.0        21.0  매우좋음  
8                  NaN  31.0  48.0        29.0  매우좋음  
9                  NaN  32.0   NaN        15.0  매우좋음

1-2) 컬럼 별 결측치 개수를 구하세요.

In [6]:
df.isnull().sum()

측정일자            3
측정시간            8
지역              9
지역명             9
도로명           194
시작점           151
종점             63
기온             12
습도             32
재비산먼지 평균농도      4
오염범례           27
dtype: int64

1-3) '도로명', '시작점', '종점' 컬럼을 삭제해주세요. <p>
(결측값 데이터 처리 - 데이터 제거) <p>
hint) 컬럼 기준 thresh 사용

In [7]:
df = df.drop(columns = ['도로명','시작점','종점'])
df

측정일자   측정시간   지역  지역명         기온    습도  재비산먼지 평균농도  오염범례
0    2021-07-01   9:44   서울  구로구  28.000000  57.0        27.0  매우좋음
1    2021-07-01  10:04   서울  구로구  28.000000  58.0        18.0  매우좋음
2    2021-07-01  10:28   서울  구로구  29.000000  54.0        33.0  매우좋음
3    2021-07-01  10:35   서울  구로구  29.000000  54.0        19.0  매우좋음
4    2021-07-01  11:04   서울  구로구  29.000000  56.0        23.0  매우좋음
..          ...    ...  ...  ...        ...   ...         ...   ...
297  2021-07-07  14:17   경기  화성시  29.000000  96.0        10.0  매우좋음
298  2021-07-07  14:27   경기  화성시  29.000000  94.0        86.0    좋음
299  2021-07-07  14:36   경기  화성시  29.000000  94.0        15.0  매우좋음
300         NaN    NaN  NaN  NaN        NaN   NaN         NaN   NaN
301         NaN    NaN  NaN  NaN  28.290657   NaN         NaN   NaN

[302 rows x 8 columns]

1-4) '측정 일자', '측정 시간', '지역', '지역명'의 결측값을 바로 아래 데이터로 대치해주세요. <p>
(결측값 데이터 처리 - 데이터 대치)

In [14]:
df.loc[:,:'지역명'].fillna(method='bfill')
df

측정일자   측정시간   지역  지역명         기온    습도  재비산먼지 평균농도  오염범례
0    2021-07-01   9:44   서울  구로구  28.000000  57.0        27.0  매우좋음
1    2021-07-01  10:04   서울  구로구  28.000000  58.0        18.0  매우좋음
2    2021-07-01  10:28   서울  구로구  29.000000  54.0        33.0  매우좋음
3    2021-07-01  10:35   서울  구로구  29.000000  54.0        19.0  매우좋음
4    2021-07-01  11:04   서울  구로구  29.000000  56.0        23.0  매우좋음
..          ...    ...  ...  ...        ...   ...         ...   ...
297  2021-07-07  14:17   경기  화성시  29.000000  96.0        10.0  매우좋음
298  2021-07-07  14:27   경기  화성시  29.000000  94.0        86.0    좋음
299  2021-07-07  14:36   경기  화성시  29.000000  94.0        15.0  매우좋음
300         NaN    NaN  NaN  NaN  28.290657   NaN         NaN   NaN
301         NaN    NaN  NaN  NaN  28.290657   NaN         NaN   NaN

[302 rows x 8 columns]

1-5) '기온', '습도'의 결측값은 각 열의 평균값으로 대치해주세요 <p>
(결측값 데이터 처리 - 데이터 대치)

In [15]:
df['기온']=df['기온'].fillna(df['기온'].mean())
df['습도']=df['습도'].fillna(df['습도'].mean())
df

측정일자   측정시간   지역  지역명         기온         습도  재비산먼지 평균농도  오염범례
0    2021-07-01   9:44   서울  구로구  28.000000  57.000000        27.0  매우좋음
1    2021-07-01  10:04   서울  구로구  28.000000  58.000000        18.0  매우좋음
2    2021-07-01  10:28   서울  구로구  29.000000  54.000000        33.0  매우좋음
3    2021-07-01  10:35   서울  구로구  29.000000  54.000000        19.0  매우좋음
4    2021-07-01  11:04   서울  구로구  29.000000  56.000000        23.0  매우좋음
..          ...    ...  ...  ...        ...        ...         ...   ...
297  2021-07-07  14:17   경기  화성시  29.000000  96.000000        10.0  매우좋음
298  2021-07-07  14:27   경기  화성시  29.000000  94.000000        86.0    좋음
299  2021-07-07  14:36   경기  화성시  29.000000  94.000000        15.0  매우좋음
300         NaN    NaN  NaN  NaN  28.290657  75.640741         NaN   NaN
301         NaN    NaN  NaN  NaN  28.290657  75.640741         NaN   NaN

[302 rows x 8 columns]

1-6) '오염범례'의 결측값은 최빈값을 먼저 파악한 뒤, 최빈값으로 대치해주세요.  <p>
(결측값 데이터 처리 - 데이터 대치)

In [17]:
print(df['오염범례'].value_counts())
df['오염범례'] = df['오염범례'].fillna('매우좋음')

매우좋음    218
좋음       40
보통        9
나쁨        6
매우나쁨      2
Name: 오염범례, dtype: int64


1-7) '지역명'이 중복되는 데이터는 가장 마지막 데이터만 남겨서 중복값을 처리해주세요. <p>
(중복값 데이터 처리)

In [18]:
df.drop_duplicates(subset='지역명',keep='last')

측정일자   측정시간   지역      지역명         기온         습도  재비산먼지 평균농도  오염범례
16   2021-07-01  13:49   서울      구로구  31.000000  48.000000       152.0    나쁨
29   2021-07-01  12:03   인천      부평구  30.000000  70.000000        20.0  매우좋음
37   2021-07-01  11:41   서울      금천구  31.000000  64.000000         3.0  매우좋음
44   2021-07-01  13:37   인천       동구  31.000000  68.000000        58.0    좋음
96   2021-07-02  13:54   경기      하남시  32.000000  56.000000       120.0    보통
106  2021-07-02  13:05   경기      안성시  30.000000  62.000000        11.0  매우좋음
109  2021-07-02  11:11   경기  용인시 수지구  27.000000  89.000000         4.0  매우좋음
141  2021-07-05  13:04   경기      파주시  26.000000  62.000000        79.0    좋음
156  2021-07-05  13:37   서울      종로구  27.000000  81.000000        12.0  매우좋음
182  2021-07-05  12:06   경기  용인시 처인구  26.000000  91.000000        24.0  매우좋음
190  2021-07-05  13:20   경기  용인시 기흥구  27.000000  86.000000         8.0  매우좋음
221  2021-07-06  15:43   서울      송파구  31.000000  75.640741        42.0  매우좋음
238  2021-07-06  14:09   경기      시흥시  29.000000  75.640741        75.0    좋음
248  2021-07-06  12:38   경기      구리시  30.000000  70.000000        56.0    좋음
256  2021-07-07  12:41   경기  안산시 상록구  27.000000  72.000000        19.0  매우좋음
261  2021-07-07  14:27   경기  안산시 단원구  29.000000  65.000000       213.0  매우나쁨
278  2021-07-07  14:39   경기      부천시  30.000000  87.000000        17.0  매우좋음
299  2021-07-07  14:36   경기      화성시  29.000000  94.000000        15.0  매우좋음
301         NaN    NaN  NaN      NaN  28.290657  75.640741         NaN  매우좋음

### 2.레이블 인코딩
Seaborn 패키지에 있는 titanic 데이터를 이용해 레이블 인코딩을 진행해보도록 하겠습니다. <p>


In [22]:
from sklearn.preprocessing import LabelEncoder

titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

2-1) titanic에 있는 class 컬럼을 레이블 인코딩해서 c_labels에 저장해주세요



In [33]:
# c_labels,index = pd.factorize(titanic['class'],sort=True)
# c_labels
encoder = LabelEncoder()
encoder.fit(titanic['class'])
c_labels = encoder.transform(titanic['class'])
c_labels

array([2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 0, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0,
       2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,

2-2) 레이블 인코딩해준 class 컬럼의 각 범주가 어떤 숫자로 변환되었는지 for문과 enumerate를 통해 확인해주세요.

In [35]:
for i, j in enumerate(encoder.classes_):
  print(j,' -->',i)

First  --> 0
Second  --> 1
Third  --> 2


2-3) 인코딩해준 값 c_labels을 다시 디코딩해주세요

In [36]:
encoder.inverse_transform(c_labels)

array(['Third', 'First', 'Third', 'First', 'Third', 'Third', 'First',
       'Third', 'Third', 'Second', 'Third', 'First', 'Third', 'Third',
       'Third', 'Second', 'Third', 'Second', 'Third', 'Third', 'Second',
       'Second', 'Third', 'First', 'Third', 'Third', 'Third', 'First',
       'Third', 'Third', 'First', 'First', 'Third', 'Second', 'First',
       'First', 'Third', 'Third', 'Third', 'Third', 'Third', 'Second',
       'Third', 'Second', 'Third', 'Third', 'Third', 'Third', 'Third',
       'Third', 'Third', 'Third', 'First', 'Second', 'First', 'First',
       'Second', 'Third', 'Second', 'Third', 'Third', 'First', 'First',
       'Third', 'First', 'Third', 'Second', 'Third', 'Third', 'Third',
       'Second', 'Third', 'Second', 'Third', 'Third', 'Third', 'Third',
       'Third', 'Second', 'Third', 'Third', 'Third', 'Third', 'First',
       'Second', 'Third', 'Third', 'Third', 'First', 'Third', 'Third',
       'Third', 'First', 'Third', 'Third', 'Third', 'First', 'First',
    

### 3.원핫 인코딩
이어서 Seaborn 패키지에 있는 titanic 데이터를 이용해 원핫 인코딩을 진행해보도록 하겠습니다. <p>


In [37]:
from sklearn.preprocessing import OneHotEncoder

titanic = sns.load_dataset('titanic')

3-1) 타이타닉에 있는 embarked 열을 원핫 인코딩해서 oh_labels에 저장해주세요

In [39]:
o_encoder = OneHotEncoder()

o_encoder.fit(titanic[['embarked']])

oh_labels = o_encoder.transform(titanic[['embarked']])


3-2) 원핫 인코딩한 결과인 embarked를 Array 형태로 출력해주세요.

In [41]:
oh_labels = oh_labels.toarray()
print(oh_labels)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### 4. Feature Scaling
마지막 Feature Scaling은 iris 데이터셋을 활용하여 표준화와 정규화를 진행하도록 하겠습니다.  <p>

In [13]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns= iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

4-1) iris 데이터에 대해 표준화 하기 전 평균과 분산, 표준화하고 나서의 평균과 분산을 출력하시오.

In [16]:

standard_scaler = StandardScaler()
#iris_df = iris_df.to_numpy()

print('표준화하기 전')
print('feature 평균')
print(iris_df.mean())
print('feature 분산')
print(iris_df.var())

print('표준화한 이후')
standard_scaler.fit(iris_df)
iris_scaled = standard_scaler.transform(iris_df)
scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 평균')
print(scaled.mean())
print('feature 분산')
print(scaled.var())

표준화하기 전
feature 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
표준화한 이후
feature 평균
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 분산
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


4-2) iris 데이터를 정규화를 한 뒤, 최대값과 최소값을 출력해주세요.

In [17]:
scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 최소값')
print(iris_df_scaled.min())
print('feature 최대값')
print(iris_df_scaled.max())

feature 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#수고하셨습니다! 제출 마감 날짜는 8월 31일 (수요일) 23시 59분입니다!
파일명 주의해주세요~! (10기_n주차_복습과제_홍길동)

제출 링크: : https://forms.gle/RyoD7zW5vLB4eKFh6